import "./globals.css";
import Header from "../components/header/header";
import MyParticles from "@/components/particlesFg";

export const metadata = {
  title: "HomePage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col justify-start">
        <Header />
        {children}
        <MyParticles />
      </body>
    </html>
  );
}
